global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'hello-service-app'
    metrics_path: /grandchild-service/actuator/prometheus
    static_configs:
      - targets: ['host.docker.internal:8082']